M48
; DRILL file {KiCad (6.0.9)} date Wed Feb 22 02:08:23 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-22T02:08:23+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1063
%
G90
G05
T1
X2.532Y-3.6
X3.75Y-1.75
X4.5Y-5.1
X5.626Y-3.65
X6.75Y-5.1
X7.5Y-1.75
X8.975Y-1.75
X9.0Y-3.6
T0
M30
